language: python

python:
 - "2.7"
 - "3.4"

install: 
 - pip install -r requirements.txt
 - pip install -r requirements_test.txt
 - pip install python-coveralls==2.5.0

script: nosetests --with-coverage --cover-erase --cover-package=flask_error_handler

after_success:
  - coveralls
