language: python

python:
 - "2.7"

install: 
 - pip install -r requirements.txt
 - pip install -r requirements_test.txt
 - pip install coveralls==0.5

script: nosetests --with-coverage --cover-erase --cover-package=flask_error_handler

after_success:
  - coveralls
